before_install:
  - sudo apt-get update
  - sudo apt-get install make autoconf dash

install:
  - cd resources && sudo make install PREFIX=/usr

# command to run tests
script: 
  - make check ARGBASH_EXEC=argbash ARGBASH_INIT_EXEC=argbash-init
